server:
  port: 8081
keycloak-config:
  server-url: http://localhost:9090
  client-id: rsa-service
  realm: Allianz
vault-config:
  url: http://localhost:8200
  policy: rsa-policy
  token: s.wX1l3DjkrOW5MqSOaW6pxnY1
database-config:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/rsa_db
spring:
  jpa:
    hibernate:
      ddl-auto: update
