server:
  port: 8763
logs-service:
  ribbon:
    listOfServers: ${LOGS_SERVICE_LIST_OF_SERVERS:http://localhost:8080}
rsa-service:
  ribbon:
    listOfServers: ${RSA_SERVICE_LIST_OF_SERVERS:http://localhost:8082}
login-service:
  ribbon:
    listOfServers: ${LOGIN_SERVICE_LIST_OF_SERVERS:http://localhost:8084}
config-server:
  ribbon:
    listOfServers: ${CONFIG_SERVER_LIST_OF_SERVERS:http://localhost:9999}
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true
zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health, prometheus
      path-mapping.prometheus: metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      cache.time-to-live: 1ms