server:
  port: 8083
keycloak-config:
  server-url: ${KEYCLOAK_URL:http://localhost:9090}
  client-id: rsa-service
  realm: Allianz
vault-config:
  url: ${VAULT_URL:http://localhost:8200}
  policy: rsa-policy
  token: s.wX1l3DjkrOW5MqSOaW6pxnY1
database-config:
  driver-class-name: com.mysql.jdbc.Driver
  url: ${DATABASE_URL:jdbc:mysql://localhost:3306/rsa_db}
spring:
  jpa:
    hibernate:
      ddl-auto: update
log-service-config:
  web-client:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/json'
    accept-type: 'application/json'
    base-url: ${LOG_SERVICE_BASEURL:http://localhost:8082/logs-service}
  write-log:
    method: POST
    uri: "/log"
    accept: ${log-service-config.webclient.accept-type}