kafka-config:
  schema-registry-url-key: schema.registry.url
  topic-names-to-create: logs-topic
  bootstrap-servers: ${KAFKA-CONFIG_BOOTSTRAP-SERVERS:localhost:19092, localhost:29092, localhost:39092}
  topic-name: logs-topic
  schema-registry-url: ${KAFKA-CONFIG_SCHEMA-REGISTRY-URL:http://localhost:9091}
retry-config:
  max-interval-ms: '10000'
  maxAttempts: '3'
  initial-interval-ms: '1000'
  sleep-time-ms: '2000'
  multiplier: '2.0'
kafka-consumer-config:
  consumer-group-id: logs-topic-consumer
  session-timeout-ms: '10000'
  max-partition-fetch-bytes-default: '1048576'
  max-partition-fetch-bytes-boost-factor: '1'
  auto-offset-reset: earliest
  batch-listener: 'true'
  specific-avro-reader-key: specific.avro.reader
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  max-poll-interval-ms: '300000'
  poll-timeout-ms: '150'
  heartbeat-interval-ms: '3000'
  auto-startup: 'false'
  max-poll-records: '500'
  specific-avro-reader: 'true'
  concurrency-level: '3'
elastic-config:
  socket-timeout-ms: '30000'
  index-name: logs-index
  connection-url: http://${ELASTIC_HOST:localhost}:${ELASTIC_PORT:9200}/
  connect-timeout-ms: '5000'
  is-repository: 'true'
server:
  port: '9192'